import { CarModels } from '../../core/database/seed/data.seed.js';

export const carMakes = CarModels.makeOptions;
export const carModels = Object.values(CarModels.modelOptions).flat();
export const carYears = CarModels.yearOptions;
export const carStatuses = CarModels.statusOptions;

export interface CarVinInfoExternal {
  success: boolean;
  input: {
    key: string;
    vin: string;
  };
  attributes: {
    year: string;
    make: string;
    model: string;
    trim: string;
    style: string;
    type: string;
    size: string;
    category: string;
    made_in: string;
    made_in_city: string;
    doors: string;
    fuel_type: string;
    fuel_capacity: string;
    city_mileage: string;
    highway_mileage: string;
    engine: string;
    engine_size: string;
    engine_cylinders: string;
    transmission: string;
    transmission_short: string;
    transmission_type: string;
    transmission_speeds: string;
    drivetrain: string;
    anti_brake_system: string;
    steering_type: string;
    curb_weight: string;
    gross_vehicle_weight_rating: string;
    overall_height: string;
    overall_length: string;
    overall_width: string;
    wheelbase_length: string;
    standard_seating: string;
    invoice_price: string;
    delivery_charges: string;
    manufacturer_suggested_retail_price: string;
    production_seq_number: string;
    front_brake_type: string;
    rear_brake_type: string;
    turning_diameter: string;
    front_suspension: string;
    rear_suspension: string;
    front_spring_type: string;
    rear_spring_type: string;
    tires: string;
    front_headroom: string;
    rear_headroom: string;
    front_legroom: string;
    rear_legroom: string;
    front_shoulder_room: string;
    rear_shoulder_room: string;
    front_hip_room: string;
    rear_hip_room: string;
    interior_trim: string[];
    exterior_color: string[];
    curb_weight_manual: string;
    ground_clearance: string;
    track_front: string;
    track_rear: string;
    cargo_length: string;
    width_at_wheelwell: string;
    width_at_wall: string;
    depth: string;
    optional_seating: string;
    passenger_volume: string;
    cargo_volume: string;
    standard_towing: string;
    maximum_towing: string;
    standard_payload: string;
    maximum_payload: string;
    maximum_gvwr: string;
  };
  colors: {
    category: string;
    name: string;
  }[];
  equipment: {
    [key: string]: string;
  };
  warranties: {
    type: string;
    miles: string;
    months: string;
  }[];
  timestamp: string;
}

export interface CarVinInfoInternal {
  attributes: {
    year: string;
    make: string;
    model: string;
    trim: string;
    style: string;
    type: string;
    size: string;
    category: string;
    madeIn: string;
    madeInCity: string;
    doors: string;
    fuelType: string;
    fuelCapacity: string;
    cityMileage: string;
    highwayMileage: string;
    engine: string;
    engineSize: string;
    engineCylinders: string;
    transmission: string;
    transmissionShort: string;
    transmissionType: string;
    transmissionSpeeds: string;
    drivetrain: string;
    antiBrakeSystem: string;
    steeringType: string;
    curbWeight: string;
    grossVehicleWeightRating: string;
    overallHeight: string;
    overallLength: string;
    overallWidth: string;
    wheelbaseLength: string;
    standardSeating: string;
    invoicePrice: string;
    deliveryCharges: string;
    manufacturerSuggestedRetailPrice: string;
    productionSeqNumber: string;
    frontBrakeType: string;
    rearBrakeType: string;
    turningDiameter: string;
    frontSuspension: string;
    rearSuspension: string;
    frontSpringType: string;
    rearSpringType: string;
    tires: string;
    frontHeadroom: string;
    rearHeadroom: string;
    frontLegroom: string;
    rearLegroom: string;
    frontShoulderRoom: string;
    rearShoulderRoom: string;
    frontHipRoom: string;
    rearHipRoom: string;
    interiorTrim: string[];
    exteriorColor: string[];
    curbWeightManual: string;
    groundClearance: string;
    trackFront: string;
    trackRear: string;
    cargoLength: string;
    widthAtWheelwell: string;
    widthAtWall: string;
    depth: string;
    optionalSeating: string;
    passengerVolume: string;
    cargoVolume: string;
    standardTowing: string;
    maximumTowing: string;
    standardPayload: string;
    maximumPayload: string;
    maximumGvwr: string;
  };
  colors: {
    category: string;
    name: string;
  }[];
  equipment: {
    [key: string]: string;
  };
  warranties: {
    type: string;
    miles: string;
    months: string;
  }[];
}

export interface IMarketValue {
  roughTradeIn: string;
  minAdjRetail: string;
  minAdjCleanTrade: string;
  tradeIn: string;
  body: string;
  minAdjRoughTrade: string;
  retail: string;
  msrp: string;
  adjustedCleanTrade: string;
  vin: string;
  model: string;
  make: string;
  adjustedCleanRetail: string;
  averageTradeIn: string;
  minMileageAdj: string;
  tradeInValues: string[];
  mileageAdjustment: string;
  maxMileageAdj: string;
  modelYear: string;
  minAdjLoan: string;
  averageMileage: string;
  adjustedAverageTrade: string;
  adjustedLoan: string;
  fuelType: string;
  success: boolean;
  minAdjAverageTrade: string;
  loanValue: string;
  adjustedRoughTrade: string;
}
