export const CarModels = {
  makeOptions: [
    'Acura',
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Bentley',
    'BMW',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Dodge',
    'Ferrari',
    'Fiat',
    'Ford',
    'Genesis',
    'GMC',
    'Honda',
    'Hyundai',
    'INFINITI',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lamborghini',
    'Land Rover',
    'Lexus',
    'Lincoln',
    'Lotus',
    'Maserati',
    'Mazda',
    'McLaren',
    'Mercedes-Benz',
    'MINI',
    'Mitsubishi',
    'Nissan',
    'Porsche',
    'Ram',
    'Rolls-Royce',
    'Subaru',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo',
  ],
  modelOptions: {
    Acura: ['ILX', 'TLX', 'RLX', 'RDX', 'MDX'],
    'Alfa Romeo': ['Giulia', 'Stelvio'],
    'Aston Martin': ['DB11', 'Vantage', 'DBS Superleggera'],
    Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
    Bentley: ['Bentayga', 'Continental GT', 'Flying Spur'],
    BMW: [
      '2 Series',
      '3 Series',
      '4 Series',
      '5 Series',
      '6 Series',
      '7 Series',
      '8 Series',
      'X1',
      'X2',
      'X3',
      'X4',
      'X5',
      'X6',
      'X7',
      'Z4',
      'i3',
      'i8',
    ],
    Buick: ['Encore', 'Envision', 'Enclave'],
    Cadillac: ['CT4', 'CT5', 'CT6', 'Escalade', 'XT4', 'XT5', 'XT6'],
    Chevrolet: [
      'Spark',
      'Sonic',
      'Malibu',
      'Impala',
      'Camaro',
      'Corvette',
      'Trax',
      'Trailblazer',
      'Equinox',
      'Blazer',
      'Traverse',
      'Tahoe',
      'Suburban',
      'Colorado',
      'Silverado',
      'Bolt EV',
      'Volt',
    ],
    Chrysler: ['300', 'Pacifica'],
    Dodge: ['Charger', 'Challenger', 'Durango'],
    Ferrari: ['812 Superfast', 'F8 Tributo', 'SF90 Stradale'],
    Fiat: ['500'],
    Ford: [
      'Mustang',
      'Fusion',
      'Taurus',
      'Focus',
      'Escape',
      'Edge',
      'Explorer',
      'Expedition',
      'Ranger',
      'F-150',
      'Super Duty',
      'Transit',
      'Bronco',
      'Mach-E',
    ],
    Genesis: ['G70', 'G80', 'G90'],
    GMC: ['Terrain', 'Acadia', 'Yukon', 'Sierra 1500', 'Canyon'],
    Honda: [
      'Accord',
      'Civic',
      'Insight',
      'Fit',
      'HR-V',
      'CR-V',
      'Pilot',
      'Passport',
      'Ridgeline',
      'Odyssey',
      'Clarity',
      'Crosstour',
    ],
    Hyundai: [
      'Accent',
      'Elantra',
      'Sonata',
      'Veloster',
      'Kona',
      'Venue',
      'Tucson',
      'Santa Fe',
      'Palisade',
      'Nexo',
    ],
    INFINITI: ['Q50', 'Q60', 'Q70', 'QX50', 'QX60', 'QX80'],
    Jaguar: ['XE', 'XF', 'XJ', 'F-PACE', 'E-PACE', 'I-PACE'],
    Jeep: ['Wrangler', 'Gladiator', 'Cherokee', 'Grand Cherokee', 'Renegade', 'Compass'],
    Kia: [
      'Rio',
      'Forte',
      'Optima',
      'K5',
      'Cadenza',
      'Stinger',
      'Soul',
      'Seltos',
      'Sportage',
      'Sorento',
      'Telluride',
      'Sedona',
    ],
    Lamborghini: ['Huracan', 'Aventador', 'Urus'],
    'Land Rover': [
      'Range Rover',
      'Range Rover Sport',
      'Range Rover Velar',
      'Range Rover Evoque',
      'Discovery',
      'Discovery Sport',
    ],
    Lexus: ['IS', 'ES', 'GS', 'LS', 'UX', 'NX', 'RX', 'GX', 'LX', 'RC', 'LC'],
    Lincoln: ['Corsair', 'Nautilus', 'Aviator', 'Navigator'],
    Lotus: ['Evora GT', 'Exige'],
    Maserati: ['Ghibli', 'Quattroporte', 'Levante'],
    Mazda: ['Mazda3', 'Mazda6', 'MX-5 Miata', 'CX-3', 'CX-30', 'CX-5', 'CX-9'],
    McLaren: ['540C', '570S', '720S', 'GT'],
    'Mercedes-Benz': [
      'A-Class',
      'C-Class',
      'E-Class',
      'S-Class',
      'CLA',
      'CLS',
      'AMG GT',
      'GLA',
      'GLC',
      'GLE',
      'GLS',
      'GLB',
      'GLE Coupe',
      'GLS Coupe',
      'SLC',
      'SL',
      'EQC',
      'Sprinter',
      'Metris',
    ],
    MINI: ['Hardtop 2 Door', 'Hardtop 4 Door', 'Countryman', 'Clubman', 'Convertible'],
    Mitsubishi: [
      'Mirage',
      'Mirage G4',
      'Outlander Sport',
      'Eclipse Cross',
      'Outlander',
      'Pajero',
      'Lancer',
    ],
    Nissan: [
      'Versa',
      'Sentra',
      'Altima',
      'Maxima',
      '370Z',
      'GT-R',
      'Kicks',
      'Rogue Sport',
      'Rogue',
      'Murano',
      'Pathfinder',
      'Armada',
      'Frontier',
      'Titan',
      'NV200',
      'Leaf',
    ],
    Porsche: ['911', '718 Boxster', '718 Cayman', 'Taycan', 'Panamera', 'Macan', 'Cayenne'],
    Ram: ['1500', '2500', '3500', 'Chassis Cab', 'ProMaster', 'ProMaster City'],
    'Rolls-Royce': ['Ghost', 'Phantom', 'Cullinan', 'Dawn', 'Wraith'],
    Subaru: ['Impreza', 'Legacy', 'WRX', 'BRZ', 'Crosstrek', 'Forester', 'Outback', 'Ascent'],
    Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y'],
    Toyota: [
      'Yaris',
      'Corolla',
      'Camry',
      'Avalon',
      '86',
      'Sienna',
      'Prius',
      'Mirai',
      'RAV4',
      'C-HR',
      'Venza',
      'Highlander',
      '4Runner',
      'Sequoia',
      'Tacoma',
      'Tundra',
      'Supra',
    ],
    Volkswagen: ['Golf', 'Jetta', 'Passat', 'Arteon', 'Tiguan', 'Atlas', 'ID.4'],
    Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
  },
  yearOptions: [
    '1990',
    '1991',
    '1992',
    '1993',
    '1994',
    '1995',
    '1996',
    '1997',
    '1998',
    '1999',
    '2000',
    '2001',
    '2002',
    '2003',
    '2004',
    '2005',
    '2006',
    '2007',
    '2008',
    '2009',
    '2010',
    '2011',
    '2012',
    '2013',
    '2014',
    '2015',
    '2016',
    '2017',
    '2018',
    '2019',
    '2020',
    '2021',
    '2022',
    '2023',
  ],
  statusOptions: ['Available', 'Sold', 'Reserved', 'Pending', 'In Trasit'],
};
